#pragma once

using namespace ATL;

template <class T>
class CProxy_IPolyCtlEvents : public IConnectionPointImpl<T, &__uuidof(_IPolyCtlEvents), CComDynamicUnkArray>
{
	// WARNING: This class may be regenerated by the wizard
public:
};
